---
title: "data.Table/dplyr/plyr"
author: "Montse Figueiro"
date: "7 de junio de 2016"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##**Ejercicio tasa.paro**

En cada periodo, calcula el porcentaje de parados que aporta cada provincia (de manera 
que la suma de los porcentajes de todas las provincias sumen el 100% en cada periodo. 
Hazlo para el total por sexos (hombres + mujeres). Usa los tres paquetes: `plyr`, 
`data.table` y `dplyr`.

###**Con data.table:**

```{r,warning=FALSE}
library(data.table)
paro <- read.table("paro.csv", header = T, sep = "\t")
paro$Periodo <- gsub("IV",  "4", paro$Periodo)
paro$Periodo <- gsub("III", "3", paro$Periodo)
paro$Periodo <- gsub("II",  "2", paro$Periodo)
paro$Periodo <- gsub("I",   "1", paro$Periodo)

paro$Situation <- as.character(paro$Situation)

paro$Situation[paro$Situation == "Active population"]   <- "active"
paro$Situation[paro$Situation == "Inactive persons"]    <- "inactive"


paro$Situation[paro$Situation == "Unemployed persons"]  <- "unemployed"
paro$Situation[paro$Situation == "Employed persons"]    <- "employed"
paro$Situation[paro$Situation == "Parados que buscan primer empleo"]    <- "never_employed"

paro$Situation <- factor(paro$Situation)
```

```{r}
parados <- paro[paro$Situation=="unemployed",]
parados.dt <- data.table(parados)
res <- parados.dt[, list(total = sum(value)), by = c("Periodo", "Provinces")]
res2 <- res[, pct := 100* total / sum(total), by = c("Periodo")]
head(res2)
```
####*comprobación:*
```{r}
a <- res2[res2$Periodo=="2014Q4",]
sum(a$pct)
sum(res2$pct)#igual a 16, cada periodo suma le 100%
unique(res2$Periodo) # hay 16 periodos diferentes
```
###**Con plyr:**

```{r,warning=FALSE}
library(plyr)
parados2 <- parados
sum(parados2$value)
parados2$Gender <- NULL
 prueba2 <- ddply(parados2, .(Periodo,Provinces), plyr::summarize, total= sum(value))
 prueba2 <- ddply(prueba2,.(Periodo),transform,pct=100*total/sum(total))
 head(prueba2)
 sum(prueba2$total)
```
####*comprobación:*

```{r}
 sum(prueba2$pct)
```
###**Con dplyr:**

```{r,warning=FALSE,message=FALSE}
library(dplyr)
parados <- paro[paro$Situation=="unemployed",]
prueba3 <- parados%>%dplyr::select(Periodo,Provinces,value)%>%group_by(Provinces,Periodo)%>%
    mutate(tottal=sum(value))%>%dplyr::select(Periodo,Provinces,tottal)%>%filter(!duplicated(Provinces))%>%
    group_by(Periodo)%>%mutate(pct=100*tottal/sum(tottal))
prueba3
```
####*comprobación:*
```{r}
sum(prueba3$pct) #16 esto si que representa 100% cada periodo, porcentaje que cada provincia representa en cada periodo.
```
